[chore] Setup yarn v3.4.1
monterail/zeppelins-fullfrontend pull request #14
Opened 2023-02-22 15:10 UTC by tomekskuta-monterail

2023-02-22 15:15 UTC, zakrzaq approved these changes

2023-02-22 15:50 UTC, WawrzenskiPatryk requested changes
Just one minor thing there 😄

2023-02-22 15:50 UTC, WawrzenskiPatryk commented on .gitignore
> +!.yarn/versions
new line 🤓 🚫

2023-02-22 15:50 UTC, WawrzenskiPatryk commented on README.md
> +
💪

2023-02-23 09:55 UTC, WawrzenskiPatryk approved these changes
LGTM 😄 ✅

2023-02-23 09:56 UTC, merged