[chore] fix TS post BE update
monterail/zeppelins-fullfrontend pull request #25
Opened 2023-03-16 11:27 UTC by zakrzaq

fix typescript issues relating to types return form `useProduct*` not being compatible with types used on FE

2023-03-16 11:58 UTC, elmir-ismayilzada approved these changes
👍

2023-03-16 13:14 UTC, zakrzaq commented
@szymonlicau @maciejkorolik Could you wage in with your experiance on matter of generated types from Supabase vs us declaring our own based on generated types. I think subject came up earlier and I was under the impression that this is the way to do it to be able to pass those on to out components for consumption? Is there is better way that I' not aware of?

2023-03-16 15:03 UTC, maciejkorolik commented
And why the generated ones won't work here?

2023-03-16 15:32 UTC, zakrzaq commented
> And why the generated ones won't work here?

I am just not sure how would we reference them in for example props?

2023-03-16 16:05 UTC, maciejkorolik commented
> I am just not sure how would we reference them in for example props?

But in `vueQuery` it works when you just use the generated types, right? So I would leave it there as it was and if you need the types in other places too, then creating your own is ok, but I'd suggest doing it like this:
```ts
export interface Product = Database["public"]["Tables"]["products"]["Row"]
```
WDYT? Then even if the generated types get updated, you are safe as you are always referencing them.

2023-03-16 16:06 UTC, WawrzenskiPatryk requested changes

2023-03-16 16:06 UTC, WawrzenskiPatryk commented on documentation/0005-sp-generated-types.md
> +Superbase allows for automatic types generation using:
> Superbase

🤔 😅

2023-03-16 16:06 UTC, WawrzenskiPatryk commented on documentation/0005-sp-generated-types.md
> +```
You can use ` ```js `, ` ```ts `, ` ```vue ` etc. instead of a ` ``` ` for syntax highlighting in markdown 😄

2023-03-16 16:06 UTC, WawrzenskiPatryk commented on documentation/0005-sp-generated-types.md
> +We need additional interfaces / types declared to make sure data coming from `Supabase` and consumed on frontend is matching and now throwing TS errors.
"_**now**_ throwing TS errors" - a typo?

2023-03-17 09:31 UTC, szymonlicau commented
I think the issue with types here is due to nested tables and supabase recommends to construct own types - and you can do it by utilizing existing, generated types 🤔 
https://supabase.com/docs/reference/javascript/typescript-support#nested-tables

2023-03-17 10:29 UTC, zakrzaq commented on documentation/decisions/0000-template.md
> +## Consequences
Sure, you are right, removed now. Will stick to using `adr tools`

2023-03-17 11:22 UTC, WawrzenskiPatryk reviewed
The ADR looks great to me, approach with types as well 😄 
Still left some comments just to polish it all out 🙏

2023-03-17 11:22 UTC, WawrzenskiPatryk commented on types/products.ts
>    product_specifications: ProductSpecifications;
Makes me feel much more safe about it 🚀 😄

2023-03-17 11:22 UTC, WawrzenskiPatryk commented on documentation/decisions/0005-supabase-generated-types-implementation.md
> +Superbase allows for automatic types generation using:
Still `Superbase` 🤔

2023-03-17 11:22 UTC, WawrzenskiPatryk commented on documentation/decisions/0005-supabase-generated-types-implementation.md
> +# 5. SupaBase-generated-types-implementation
I don't think it's `SupaBase` but just `Supabase`. Either way not really a request for change or something, it doesn't matter much 😄

2023-03-17 11:47 UTC, WawrzenskiPatryk approved these changes
🎉

2023-03-17 11:47 UTC, elmir-ismayilzada approved these changes
Everything is very good!

2023-03-17 11:47 UTC, elmir-ismayilzada commented on types/products.ts
Wow that's amazing! 👍

2023-03-17 11:47 UTC, elmir-ismayilzada commented on types/generated-types.ts
Like it ❤️‍🔥

2023-03-17 11:50 UTC, merged